# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.generalized_median <- function(pred) {
    .Call(`_BayesINAR_generalized_median`, pred)
}

.posterior_inar <- function(y, p, prior, burn_in, N, random_seed, verbose) {
    .Call(`_BayesINAR_posterior_inar`, y, p, prior, burn_in, N, random_seed, verbose)
}

.predictive_distribution_inar <- function(model, h, replications) {
    .Call(`_BayesINAR_predictive_distribution_inar`, model, h, replications)
}

.posterior_adinar <- function(y, p, prior, burn_in, N, random_seed, verbose) {
    .Call(`_BayesINAR_posterior_adinar`, y, p, prior, burn_in, N, random_seed, verbose)
}

.predictive_distribution_adinar <- function(model, h, replications) {
    .Call(`_BayesINAR_predictive_distribution_adinar`, model, h, replications)
}

.posterior_dpinar <- function(y, p, prior, burn_in, N, random_seed, verbose) {
    .Call(`_BayesINAR_posterior_dpinar`, y, p, prior, burn_in, N, random_seed, verbose)
}

.predictive_distribution_dpinar <- function(model, h, replications) {
    .Call(`_BayesINAR_predictive_distribution_dpinar`, model, h, replications)
}

